### ISSUE TITLE
Ici pour les questions?

### ISSUE THREAD

**Issue by idkjs** [js-republic/reason-ml-workshop#5]
How is the Store.dispatch reading the rootType? Is it reading the module name?

Je fais reference a [etape #2](https://github.com/js-republic/reason-ml-workshop#remettez-en-marche-les-propulseurs-auxiliaires---etape-2)

**Comment by mbreton** [comment]
`Store.dispatch` doesn't call directly the `rootState`, in fact, the `dispatch` will just append the action given in parameter in a list of action. Then, each time the rendering loop occurs, it iterates over all the actions to apply them on the reducers (cf. 'applyReducers' function in [`Store.re` L.74](https://github.com/js-republic/reason-ml-workshop/blob/master/src/Store.re#L74) )

**Comment by idkjs** [comment]
Ok, like any other reducer, of course. Merci.
